#!/bin/bash
# Debug script for topology generation

set -e  # Exit on error

DATA_DIR="./data"
cd "${DATA_DIR}"

echo "Checking water.pdb for MW site..."
if grep -q "MW" water.pdb; then
  echo "Detected 4-site water model (with MW site)"
else
  echo "Detected 3-site water model"
fi

echo "Counting water molecules in water_box.pdb..."
water_count=$(grep -c "OW  SOL" water_box.pdb || echo "Failed to count")
echo "Found ${water_count} water molecules"

echo "Creating topology file..."
cat > topol.top << EOF
; TIP4P/Ice water topology
; Generated by debug_topology.sh

; Include force field parameters
#define _FF_OPLS
#define _FF_OPLSAA

[ defaults ]
; nbfunc        comb-rule       gen-pairs       fudgeLJ fudgeQQ
1               3               yes             0.5     0.5

; Include the local force field files
#include "./ffnonbonded.itp"
#include "./ffbonded.itp"

; Include TIP4P/Ice water model parameters
[ atomtypes ]
; name     mass      charge   ptype    sigma        epsilon
IW     0             0.000       D   0.0           0.0
OWT4   15.99940      0.000       A   0.31668       0.88211
HW     1.00800       0.000       A   0.00000E+00   0.00000E+00

[ moleculetype ]
; name nrexcl
SOL  1

[ atoms ]
; nr type   resnr  residu atom  cgnr  charge   mass
1     OWT4  1      SOL    OW    1     0        15.9994
2     HW    1      SOL    HW1   1     0.5897   1.008
3     HW    1      SOL    HW2   1     0.5897   1.008
4     IW    1      SOL    MW    1    -1.1794   0.0

[ constraints ]
; i   j   funct   length
1       2       1       0.09572
1       3       1       0.09572
2       3       1       0.15139

[ exclusions ]
1       2       3       4
2       1       3       4
3       1       2       4
4       1       2       3

[ dummies3 ]
; Dummy from    funct   a         b
4       1       2       3       1       0.13458   0.13458

[ system ]
TIP4P/Ice Water System

[ molecules ]
; Compound        nmols
SOL               ${water_count}
EOF

echo "Topology file created."
echo "Verifying topology..."
grep -A 5 "\[ system \]" topol.top
grep -A 2 "\[ molecules \]" topol.top

echo "Debug completed." 